# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-browser
    visibility: public

tasks:
  - init: echo 'init script' # runs during prebuild
    command: npm install
